GET http://localhost:3030/records

###

GET http://localhost:3030/records?page=2&limit=10&offset=0

###

GET http://localhost:3030/records?page=2&limit=10&offset=0&color[]

###

GET http://localhost:3000/records

###

GET http://localhost:3000/records?page1=&limit=10

###
